### ISSUE TITLE
Implement a workspace service

### ISSUE THREAD

**Issue by retailcoder** [rubberduck-vba/Rubberduck3#25]
Upon initialization, add-in client should set up a virtual workspace that can have virtual folders. Loaded documents should be in this virtual namespace when working in-memory.

Service needs to:
- [ ] expose `Load` and `Unload` methods to synchronize the documents loaded in the workspace to and from the VBIDE
- [ ] expose `Import` and `Export` methods to synchronize the workspace with a physical folder in the file system (host document must be saved).
- [ ] when bound to a physical root folder, leverage a `FileSystemWatcher` to synchronize content.
- [ ] expose `CreateFolder`, `RemoveFolder`, and `RenameFolder` methods.
- [ ] expose `CreateFile`, `RemoveFile`, and `RenameFile` methods.

The abstract interface `IWorkspaceService` should be defined under `Rubberduck.Client` and implemented under `Rubberduck.Server.LSP`.

**Comment by BZngr** [comment]
Related #37

**Comment by BZngr** [comment]
Some questions regarding `WorkspaceService` (`WS`) implementation:

1. In my various attempts at implementing this service, it seems that there is always some form of an internal `Dictionary<string,string>` of _content-by-moduleName_ needed.  Should this `Dictionary` (or _Dictionary-like_ accessors) be exposed on the interface for use by the parser and the Add-in/RDE?  (I'm thinking that the parser needs access to the entire `Dictionary` while the Add-in/RDE is more module-by-module).
2. If the components in '1' above use the `WS` interface directly, then the interface described is missing accessors for this `Dictionary` - true?
3. Am I correct to expect that on `Startup`, the Add-in will initiate a VBE export of all modules to the 'Saved' `.rd` repository?  (The `WS` can provide the target folder path  => `<hostdocument parent folder>\.rd\<workspaceName>\datasets\saved` ATM).  This export seems necessary to me since it generates the best source-of-truth of hostdocument state at startup. 
4. If '3' above is a correct expectation, then subsequently invoking the `WS.Import` populates the in-memory `Dictionary` from what the `WS` finds in the 'Saved' repo. (This is the easiest use case in that it assumes no files are present in the 'Working' repo). 
5. `Load` and `Unload` look a bit like a facade to the in-memory `WS` `Dictionary` for RDE CRUD operations - true?  Or, do they imply some other (or additional) responsibilities?
6. I'm also thinking that calls to `Unload` should result in exporting the modified content/files to the 'Working' repo.

**Comment by retailcoder** [comment]
1. I think it's possible that we find the requirements evolve as we progress with the LSP implementation (e.g. exposing the module contents to the rest of the server), but for now let's treat it as a separate, out-of-scope enhancement until we implement something server-side that needs to consume it.
3. 💯 correct
5. In my mind they'd work exactly like RD2 file system synchronization does
6. 💯 exactly

**Comment by BZngr** [comment]
Thank you for those answers...in particular, `5.` was a surprise and definitely changed my understanding of the `WorkspaceService` (`WS`).  

I was thinking that the `WS` was responsible to host/provide in-memory versions of module content.  So, if the `WS` is not responsible for this, then it would seem that it's primary support responsibility is to deliver folderpaths and filepaths (by module name). 

 Consequently, the `WS` interface would seem to require the following edits:

`Import`: Remove => Per question/statement `3.` above,  the Add-in/`VBE` 'Export Active Project' capability requires a folder target.  The `WS` supports by providing the folder path of the 'Saved' repo.  

That said, the `WS` does need to know _when_ all project modules been saved/exported. So, add member like:
`void Reset()` or a `void OnAfterExportActiveProject(...)` event:

1. Clears the 'Working' repo.  All current file versions are now found in the 'Saved' repo.
2. Cleans-up files deleted/renamed in the 'Saved' repo because export operations do not remove them. (see `Remove/RenameFile` below).

`Export` : Remove => all conversions from the `VBE` to file(s) are handled by the Add-in/`VBE`.

`Unload` :  Remove =>  AIUI, this member is intended to persist RDE file edits when the RDE is closed without saving.  So, generating the files is handled by the Add-in/`VBE`.  The `WS` supports 'unloading' by providing the folder path of the 'Working' repo.

`Load` : Remove => Add-in/RDE files are loaded based on filepaths provided by the `WS`

`CreateFile`: Remove => files are created by the Add-in/`VBE` via the next RDE `Close` or host document `Save` operations.

`RemoveFile`: The `WS` tracks files that should not exist after the next `VBE` export.
 
`RenameFile`: The `WS` tracks files that should not exist after the next `VBE` export.

`Create/Remove/RenameFolder` members: I'm thinking that these are not needed due to the `.rd` folder structure that uses a flat file hierarchy.  Once we start addressing user repository folder hierarchies (e.g., Git), there may be a need for these type of members.

`IEnumerable<IFileInfo> GetFiles(params string[] moduleNames)` <= supports loading the RDE

`IDirectoryInfo SavedRepository { get; } `  <= used by Add-in/`VBE` save operations

`IDirectoryInfo WorkingRepository { get; }` <= used by Add-in/RDE unload operations

BTW: when I look at where `.notepad++` and `vscode` handle their 'Working' files, they use `backup` or `Backups` folders respectively.  Should we consider a similar name?

**Comment by retailcoder** [comment]
The interface requirements came from my own understanding of what the LSP server needs to be able to do; creating/renaming/deleting workspace folders is part of that, since LSP treats both files and folders the same (anything it can do to a file, it can do to a folder).
In my mind this workspace service would provide us with an API to access the file system.

We need separate operations for interacting with VBComponent/VBE modules vs interacting with what's loaded in the RDE; the RDE runs client-side, but isn't tied to the VBE other than being inside a toolwindow - it could just as well be a standalone application, but we want the RDE to ship as a VBIDE add-in (at least for now!), so in no situation the RDE loads anything directly from the VBE.

So on startup the add-in would call this service to determine whether a physical workspace folder exists for that project on the file system (and create it otherwise); if we're creating the folder, the truth is in the VBE and we need to export everything (most likely an empty project, but not necessarily; done by invoking the "export" functionality) to get the truth from the file system. If it already exists, then the truth is what's in that folder and we need to synchronize the VBE with it, potentially reusing functionality we wrote for RD2 (the UI command for it probably won't need to exist in RD3) / invoking the "import" functionality. So that's what `Load` would do in my mind: once the truth is in the FS all the service needs to do is fire events when a FileSystemWatcher event requires updating something, and VBE events could also conceivably notify the service about external edits and files being added or removed (external as far as the WS / source of truth is concerned).

Perhaps we're getting ahead of ourselves though. At the end of the day what we need at this point is to be able to send the _Initialize_ LSP request: https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/#initialize, and in order to do that we need a root URI and a collection of `WorkspaceFolder` objects (name+URI).
